version: "3"

services:
  app_inventario:
    build:
      context: Inventario/
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/inventario
      spring.datasource.username: root
      spring.datasource.password: Conexionlocal1
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Conexionlocal1
      MYSQL_DATABASE: inventario
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
